# Learning parameters
LEARNING_RATE = 0.1
DISCOUNT_FACTOR = 0.95
EPSILON = 0.1
NUM_EPISODES = 1000

# Game parameters
FPS = 120
STUCK_TIMEOUT_STEPS = 50  # Number of steps before timeout
SAVE_INTERVAL = 10
MAX_NEGATIVE_REWARD = 1000